### ISSUE TITLE
users.vue has a potential redundancy (and a typo)

### ISSUE THREAD

**Issue by mcat97** [aturingmachine/mevn-stack#2]
on line 151 in users.vue
`this.alertProc(falese, "Delete");` (which causes it to not happen)

you again call this during your error catch, where it is spelled correctly. I am not sure if you need both.

**Comment by aturingmachine** [comment]
Should be fixed as per [this commit ](https://github.com/aturingmachine/mevn-stack/commit/4f5811fb35e86e570d342ded7e75183af4bdcae2). Thanks.
