### ISSUE TITLE
Separate package.json for front-end and back-end

### ISSUE THREAD

**Issue by areebbeigh** [aturingmachine/mevn-stack#7]
Is it possible to be able to have independent package.json files for the server and front-end? It needs to be such that imports in the client don't resolve to the parent directory (i.e the server's `node_modules/`).

**Comment by aturingmachine** [comment]
You could very well structure it in this way if you'd like. However the idea was to have an entire stack running from a single package. If you'd like to for and create this version I'd be more than happy to take a look an possible link to it from this project.

**Comment by areebbeigh** [comment]
Ah I see. I'm still new to this. I don't really have enough experience to know what kind of file structure would be ideal 😅. Thanks though.

**Comment by aturingmachine** [comment]
No problem! Your suggestions is definitely a valid use case, just not this project's intention.
